### ISSUE TITLE
compatibility with beta of cowboy 2.0x ?

### ISSUE THREAD

**Issue by benoitc** [inaka/cowboy-trails#72]
I'm curious if someone already worked on it. Otherwise would you accept a patch for it? What could be the best way to handle both cowboy 1.0x and cowboy 2.0x ?

**Comment by jfacorro** [comment]
@benoitc I don't think supporting both cowboy 1.x.x and 2.x.x is a feasible option from a maintainability point of view. I would be happy tagging the current version as 1.0.0, updating to cowboy 2.x.x and bumping the major version as 2.0.0.

**Comment by elbrujohalcon** [comment]
I agree with @jfacorro
